version: '3.1'

services:

  comet:
    image: rencinrig/comet-spring
    container_name: comet
    volumes:
      - ~/log:/var/log #modify to your desired local directory
    restart: always
    hostname: comet
    ports:
      - 8111:8111
    environment:
      ACCUMULO_TABLENAME: trace
      ACCUMULO_ZOOSERVERS: zoo1,zoo2,zoo3
      ACCUMULO_INSTANCE: docker-development
      COMET_CHECK_TOKEN_STRENGTH: 'false'
      COMET_CHECK_CLIENT_CERT: 'false'
