rm -rf /opt/accumulo-1.9.3/
rm -rf /opt/zookeeper/
rm -rf /home/hadoop/
rm -rf zookeeper.out
rm  -rf /data/*
rm  -rf /conf/*
rm -rf /hdfsdata
rm -rf /etc/profile.d/zookeeper.sh
rm -rf /etc/profile.d/hadoop.sh
rm -rf /etc/profile.d/accumulo.sh
