version: '3.1'

services:

  comet:
    image: rencinrig/comet-spring
    container_name: comet
    volumes:
      - /var/log:/var/log #modify to your desired local directory
    restart: always
    hostname: comet
    ports:
      - 8111:8111
    extra_hosts:
      - "zoo1:192.168.100.34"
      - "zoo2:192.168.100.35"
      - "zoo3:192.168.100.31"
      - "comet-w1:192.168.100.32"
      - "comet-w2:192.168.100.33"
    environment:
      ACCUMULO_TABLENAME: trace
      ACCUMULO_ZOOSERVERS: zoo1,zoo2,zoo3
      ACCUMULO_INSTANCE: aws-development
      ACCUMULO_USER: 'changeme'
      ACCUMULO_PASSWORD: 'changeme'
      COMET_CHECK_TOKEN_STRENGTH: 'false'
      COMET_CHECK_CLIENT_CERT: 'false'
      COMET_SSL_KEY_STORE: cometserver.jks
      COMET_SSL_KEY_STORE_PWD: 'changeme'
      COMET_SSL_KEY_PWD: 'changeme'
      COMET_SSL_TRUST_STORE: comettrustedstore.jks
      COMET_SSL_TRUST_STORE_PWD: 'changeme'
    logging:
      driver: "none"
